name: Provision Synapse Data Platform
on: workflow_dispatch 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # Checkout code
    - uses: actions/checkout@v3
    
    #Log into Azure
    - uses: azure/login@v1
      with:
           creds: '{"clientId":"${{ secrets.ACTION_SPN_CLIENTID }}","clientSecret":"${{ secrets.ACTION_SPN_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'

    # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        region: australiaeast
        subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
        template: ./main.bicep
        failOnStdErr: false
